### ISSUE TITLE
Pre-Annotated Data Export Formats

### ISSUE THREAD

**Issue by rudrakshass** [DininduChamikara/Annotated-Corpus-Collection#47]
Description: The current application lacks support for exporting pre-annotated datasets in multiple formats (e.g., JSON, XML, CSV). It would be useful to allow users to export data in various formats based on their needs for further processing.

Proposed Solution: Implement functionality that allows the pre-annotated datasets to be exported in common formats like JSON, XML, and CSV. This can be achieved by adding export options that transform the existing annotation data structure into the desired formats.

Request: Please assign this issue to me. I would like to implement this feature.

**Comment by DininduChamikara** [comment]
> Description: The current application lacks support for exporting pre-annotated datasets in multiple formats (e.g., JSON, XML, CSV). It would be useful to allow users to export data in various formats based on their needs for further processing.
> 
> Proposed Solution: Implement functionality that allows the pre-annotated datasets to be exported in common formats like JSON, XML, and CSV. This can be achieved by adding export options that transform the existing annotation data structure into the desired formats.
> 
> Request: Please assign this issue to me. I would like to implement this feature.

Thank you for this feature enhancement idea. Please work on it. If you can complete it within October, I will give you a hacktoberfest-accepted label for this task.
