### ISSUE TITLE
Replace Default React Favicon with Custom Favicon

### ISSUE THREAD

**Issue by rudrakshass** [DininduChamikara/Annotated-Corpus-Collection#49]
Hi there! I noticed that the website is currently using the default React favicon. A custom favicon would improve the site’s branding and help it stand out. I’d be happy to replace it with a new favicon. Please let me know if I can work on this. Thank you!

**Comment by DininduChamikara** [comment]
> Hi there! I noticed that the website is currently using the default React favicon. A custom favicon would improve the site’s branding and help it stand out. I’d be happy to replace it with a new favicon. Please let me know if I can work on this. Thank you!

Thanks. Please work on it.

**Comment by DininduChamikara** [comment]
Thanks. Your changes deployed.
