### ISSUE TITLE
Adding tooltips to the buttons

### ISSUE THREAD

**Issue by rudrakshass** [DininduChamikara/Annotated-Corpus-Collection#50]
Adding tooltips to the main buttons could improve the user experience by making their functions clearer. I’d be happy to help implement this!

**Comment by DininduChamikara** [comment]
> Adding tooltips to the main buttons could improve the user experience by making their functions clearer. I’d be happy to help implement this!

@rudrakshass Thanks. Please work on it.

**Comment by DininduChamikara** [comment]
@rudrakshass Thanks, your code update is now live.
