### ISSUE TITLE
Updating the button styles

### ISSUE THREAD

**Issue by rudrakshass** [DininduChamikara/Annotated-Corpus-Collection#51]
I noticed that the button styles could be made more consistent with the rest of the design. I’d like to propose some updates to improve their appearance. Let me know if I can work on this!

**Comment by DininduChamikara** [comment]
> I noticed that the button styles could be made more consistent with the rest of the design. I’d like to propose some updates to improve their appearance. Let me know if I can work on this!

@rudrakshass Thanks. Please work on it.

**Comment by DininduChamikara** [comment]
@rudrakshass Thanks. Your update is live now.
